add file to prbranch (#13)
* add file to prbranch

* shot workflow

* clenup

* shot on pr

* Delete jajaj

* Delete oldbranch

* debug

* a

* b

* v0.1

* remove swp

* sleep and shot opts

* test commit

* debuggie

* newfile

* remove sleep from shot

* one

* two

* debug for pr wf

* shot step name

* v0.3 of shot

* new

* newnew

* debuggie

* ${{github.sha}}

* github.head_ref

* fuu

* debuggie

* kludge gh actions again

* look again

* one

* two

* three

* u

* uz

* zuz

* k

* l

* m

* get shot action from master

* v0.7

* a

* b

* c

* debug commit output

* d

* 3

* debug

* zone

* ztwo

* odin

* dva

* jopa

* git log

* kek

* kek2

* github ids

* v0.8

* v0.9

* v0.9.1

* v0.9.2

* 1530

* 28928

* 18208

* v0.9.3

* 16409

* 23837

* 9551

* 8379

* 25550

* v094

* 3286

* 28729

* v0.9.5

* 24279

* 13849

* 17236

* 19063

* v0.9.6

* 1259

* 4015

* 24559

* PERSONAL_TOKEN

* 25910

* 23957

* 31054

* 4408

* 10106

* 31701

* 31719

* 5947

* 10898

* 28681

* 25579

* 2782

* v1 personal token

* 30819

* 19772

* 8719

* 4227

* 6217

* v1.1

* 817

* 6440

* v1.2

* 11393

* 29995

* v1.3

* 30482

* 19554

* 15866

* 2419

* 5383

* v1.4

* 10468

* 8374

* 16487

* 19636

* 28410

* 27482

* 29230

* 11931

* 31508

* 26096

* 10100

* 22012

* v1.5

* v1.6

* fail

* fix

* random

* fail scenario

* exit0

* if: failure()

* if: failure()

* exit1

* exit0

* exit 1

* continue

* slack

* escape

* eba

* kek

* hullo

* pr notify

* pr notify

* interpola

* k3s

diff --git a/.github/workflows/shot.yaml b/.github/workflows/shot.yaml
--- a/.github/workflows/shot.yaml
+++ b/.github/workflows/shot.yaml
@@ -1,13 +1,33 @@
+name: shot
 on:
-  push:
-    branches:
-    - master
+  pull_request:
 jobs:
-  pull-request:
+  shot:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
-    - name: pull-request
-      uses: yellowmegaman/gh-build-canceller@master
+    - name: failstep
+      run:  exit 1
+    - name: debugfail
+      if: failure()
+      run:  echo "yep, it failed"
+    - name: lifecontinues
+      run:  echo "continue"
+      if: failure()
+    - name: runids
+      run:  echo "${{github.run_id}} ${{github.run_number}}"
+    - name: debug
+      run:  env | sort
+    - name: more debug
+      run:  git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)'
+    - name: commit
+      id:   commit
+      run:  echo ::set-output name=commit_sha::$(git log --skip 1 -n1 --format=format:%H)
+    - name: debugg
+      run:  echo ${{steps.commit.outputs.commit_sha}}
+    - name: shot
+      uses: yellowmegaman/gh-build-canceller@v1.6
       with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
+        github_token: ${{secrets.PERSONAL_TOKEN}}
+        workflows_filter: "CI|pr"
+        commit_sha: ${{steps.commit.outputs.commit_sha}}
